before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: tss
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - mips64
      - mips64le
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: 386
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: linux
        goarch: arm
        
archives:
  - id: tar-gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
  - id: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    files:
      - none*
    format: zip
